# Chapter 6 Exercises

## 6.2 What's Wrong with This Code?

The following code should display the unique words in the string text and the number of occurrences of each word.

```python
from collections import Counter

text = ('to be or not to be that is the question')
counter = Counter(text.split())
print(counter)
for word, count in sorted(counter):
    print(f'{word:<12}{count}')
```


The issue with this code is that the `sorted()` method converts the dictionary created by the `Counter()` function to a list. Thus, there are no key-value (word-count) pairs to be unpacked by the loop. Additionally, the `.items()` method is not called, which is required to generate tuples of each key-value pair that can then be unpacked.

Corrected:

In [16]:
from collections import Counter

text = ('to be or not to be that is the question')
counter = Counter(text.split())
for word, count in counter.items():
    print(f'{word:<12}{count}')
    

to          2
be          2
or          1
not         1
that        1
is          1
the         1
question    1


## 6.3 What Does This Code Do?

The dictionary `temperatures` contains three Fahrenheit temperature samples for each of four days. What does the `for` statement do?

```python
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}
for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')
```

This code iterates through the dictionary `temperatures` and prints out the day along with the average temperature of each day formatted with two decimal points. It does this by unpacking the key-value tuples created by the `.items()` method in each iteration of the `for` loop.

Checking:

In [1]:
temperatures = {
    'Monday': [66, 70, 74],
    'Tuesday': [50, 56, 64],
    'Wednesday': [75, 80, 83],
    'Thursday': [67, 74, 81]
}
for k, v in temperatures.items():
    print(f'{k}: {sum(v)/len(v):.2f}')


Monday: 70.00
Tuesday: 56.67
Wednesday: 79.33
Thursday: 74.00


## 6.6 Data Science: Duplicate Word Removal

Write a function that receives a list of words, then determines and displays in alphabetical order only the unique words. Treat uppercase and lowercase letters the same. The function should use a set to get the unique words in the list. Test your function with several sentences.

In [43]:
def display_sorted(word_list):
    "Remove duplicates from a list of words and display them in alphabetical order"
    
    # create set of unique words with a set comprehension, account for varying cases with .lower() method
    unique_words = {word.lower() for word in word_list}
    
    # convert back to list and sort with sorted() function
    unique_word_list = sorted(unique_words)
        
    return unique_word_list

print(display_sorted(['to', 'be', 'or', 'not', 'to', 'be']))
print(display_sorted(['To', 'be', 'or', 'Not', 'to', 'be']))
print(display_sorted(['ok', 'OK', 'test', 'list', 'with', 'duplicates', 'LIST', 'lIst']))


['be', 'not', 'or', 'to']
['be', 'not', 'or', 'to']
['duplicates', 'list', 'ok', 'test', 'with']


## 6.9 Dictionary Manipulations

Using the following dictionary, which maps country names to Internet top-level domains (TLDs):

In [5]:
# initialize tlds dictionary
tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

perform the following (a - g) tasks and display the results:

### a.

Check whether the dictionary contains the key `'Canada'`.

In [6]:
'Canada' in tlds.keys()

True

### b.

Check whether the dictionary contains the key `'France'`.

In [7]:
'France' in tlds.keys()

False

### c.

Iterate through the key–value pairs and display them in two-column format.

In [9]:
for country, tld in tlds.items():
    print(f'{country:<15} {tld}')

Canada          ca
United States   us
Mexico          mx


### d.

Add the key–value pair `'Sweden'` and `'sw'` (which is incorrect).

In [14]:
tlds['Sweden'] = 'sw'
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'sw'}

### e.

Update the value for the key `'Sweden'` to `'se'`.

In [15]:
tlds.update(Sweden = 'se')
tlds

{'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx', 'Sweden': 'se'}

### f.

Use a dictionary comprehension to reverse the keys and values.

In [16]:
tlds_flipped = {tld:country for country, tld in tlds.items()}
tlds_flipped

{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

### g.

With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.

In [17]:
tlds_countries_upper = {tld: country.upper() for tld, country in tlds_flipped.items()}
tlds_countries_upper

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

# Chapter 7 Exercises

In [18]:
import numpy as np

## 7.2 Broadcasting

Use `arange` to create a 2-by-2 `array` containing the numbers 0–3. Use broadcasting to perform each of the following (a - c) operations on the original `array`:

In [44]:
array_1 = np.arange(4).reshape(2,2)
print(array_1)

[[0 1]
 [2 3]]


### a.

Cube every element of the array.

In [45]:
cubes = array_1 ** 3
print(cubes)

[[ 0  1]
 [ 8 27]]


### b.

Add 7 to every element of the array.

In [46]:
add_7 = array_1 + 7
print(add_7)

[[ 7  8]
 [ 9 10]]


### c.

Multiply every element of the array by 2.

In [47]:
double = array_1 * 2
print(double)

[[0 2]
 [4 6]]


## 7.3 Element-Wise Array Multiplication

Create a 3-by-3 `array` containing the even integers from `2` through `18`. Create a second 3-by-3 `array` containing the integers from `9` down to `1`, then multiply the first `array` by the second.

In [48]:
array_2 = np.arange(2, 19, 2).reshape(3, 3)
print(array_2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [49]:
array_3 = np.arange(9, 0, -1).reshape(3, 3)
print(array_3)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [50]:
mult = array_2 * array_3
print(mult)

[[18 32 42]
 [48 50 48]
 [42 32 18]]


## 7.9 Data Science: Indexing and Slicing Arrays

Create an `array` containing the values 1–15, `reshape` it into a 3-by-5 `array`, then use indexing and slicing techniques to perform each of the following (a - f) operations:

In [51]:
array_4 = np.arange(1, 16).reshape(3, 5)
print(array_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### a.

Select row `2`.

In [25]:
array_4[2]

array([11, 12, 13, 14, 15])

### b.

Select column `4`.

In [26]:
array_4[:, 4]

array([ 5, 10, 15])

### c.

Select rows `0` and `1`.

In [27]:
array_4[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### d.

Select columns `2`–`4`.

In [28]:
array_4[:, 2:] # could specify 5 as the ending slice, but column 4 is the last column so this works

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

### e.

Select the element that is in row `1` and column `4`.

In [29]:
array_4[1, 4]

10

### f.

Select all elements from rows `1` and `2` that are in columns `0`, `2` and `4`.

In [30]:
array_4[1:3, [0, 2, 4]]

array([[ 6,  8, 10],
       [11, 13, 15]])

## 7.14 Data Science: Horizontal and Vertical Slicing

Create the two-dimensional `array`s:

```python
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
```

In [32]:
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])


### a.

Use vertical stacking to create the 4-by-2 `array` named `array3` with `array1` stacked on top of `array2`.

In [38]:
array3 = np.vstack((array1, array2))
print('Array 1:')
print(array1)
print('Array 2:')
print(array2)
print('Result:')
print(array3)


Array 1:
[[0 1]
 [2 3]]
Array 2:
[[4 5]
 [6 7]]
Result:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### b.

Use horizontal stacking to create the 2-by-4 `array` named `array4` with `array2` to the right of `array1`.

In [40]:
array4 = np.hstack((array1, array2))
print('Array 1:')
print(array1)
print('Array 2:')
print(array2)
print('Result:')
print(array4)


Array 1:
[[0 1]
 [2 3]]
Array 2:
[[4 5]
 [6 7]]
Result:
[[0 1 4 5]
 [2 3 6 7]]


### c.

Use vertical stacking with two copies of `array4` to create a 4-by-4 `array5`.

In [41]:
array5 = np.vstack((array4, array4))
print('Array 4:')
print(array4)
print('Result:')
print(array5)


Array 4:
[[0 1 4 5]
 [2 3 6 7]]
Result:
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]


### d.

Use horizontal stacking with two copies of `array3` to create a 4-by-4 `array6`.

In [42]:
array6 = np.hstack((array3, array3))
print('Array 3:')
print(array3)
print('Result:')
print(array6)


Array 3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Result:
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
